### ISSUE TITLE
The automagic :package:

### ISSUE THREAD

**Issue by stephlocke** [hadley/requirements#10]
Heya,
A very similar package has been on CRAN for more than a year now - would improving that or adopting it be an option?

https://CRAN.R-project.org/package=automagic
https://github.com/cole-brokamp/automagic

Cheers,
Steph

**Comment by hadley** [comment]
The dependency list for automagic suggests it has different priorities. But I don't think this package is going to be developed further anyway, and instead we'll just make sure that renv provides an exported function to do what we need.
